#!/usr/bin/env python

import sys
from teletext.raw.map import raw_line_map
from teletext.raw.pattern import Pattern
from teletext.raw.patterngpu import PatternGPU
from teletext.raw.line import Line

pg = PatternGPU('parity_patterns')

import config
Line.set_config(config)

def find_other_bits_gpu(l):
    matches = pg.match(l.bits_array[36:362])

    for b in range(40):
        l.bytes_array[b+2] = pg.bytes[matches[b]]

def doit(rl):
    l = Line(rl)
    if l.is_teletext:
        l.roll(3)
        l.bits()
        l.mrag()
        #find_other_bits_gpu(l)
    return l

for l in raw_line_map(sys.argv[1], config.line_length, doit, threads=1, show_speed=True):
    find_other_bits_gpu(l)
    l.bytes_array.tofile(sys.stdout)

