#!/usr/bin/env python

# * Copyright 2016 Alistair Buxton <a.j.buxton@gmail.com>
# *
# * License: This program is free software; you can redistribute it and/or
# * modify it under the terms of the GNU General Public License as published
# * by the Free Software Foundation; either version 3 of the License, or (at
# * your option) any later version. This program is distributed in the hope
# * that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
# * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# * GNU General Public License for more details.

import sys
from teletext.raw.map import raw_line_map
from teletext.raw.pattern import Pattern
from teletext.raw.patterngpu import PatternGPU
from teletext.raw.line import Line

pg = PatternGPU('parity_patterns')

import config
Line.set_config(config)

def find_other_bits_gpu(l):
    matches = pg.match(l.bits_array[36:362])

    for b in range(40):
        l.bytes_array[b+2] = pg.bytes[matches[b]]

def doit(rl):
    l = Line(rl)
    if l.is_teletext:
        l.roll(3)
        l.bits()
        l.mrag()
        #find_other_bits_gpu(l)
    return l

for l in raw_line_map(sys.argv[1], config.line_length, doit, threads=1, show_speed=True):
    find_other_bits_gpu(l)
    l.bytes_array.tofile(sys.stdout)

