#!/usr/bin/env python

import sys

from teletext.t42.pipeline import reader, make_service
from teletext.t42.packet import Packet

service = make_service(reader(open(sys.argv[1])))

while True:
    for packet in service.next_packets(prio=[3,3,3,3,3,3,3,3]):
        
        x = packet.to_bytes()
        if len(x) == 42 or len(x) == 0:
            sys.stdout.write(x)
        else:
            raise IndexError(type(packet), len(x))
