#!/usr/bin/env python3

# An example of generating a service from scratch.

import sys

from teletext.service import Service
from teletext.subpage import Subpage

# Create a subpage
subpage = Subpage(prefill=True)

# Fill with clock cracker
subpage.displayable[:,0::2] = 0xfe
subpage.displayable[:,1::2] = 0x7f
subpage.displayable[:,0] = 0x20

# Put a message in the middle
subpage.displayable.place_string('Hello World', 15, 11)

# Create the service
service = Service(replace_headers=True)

# Add the subpage to the service.
service.magazines[1].pages[0].subpages[0] = subpage

# Set magazine name and number
service.magazines[1].title = 'Example '

# Broadcast it forever
while True:
    # Stream some packets
    for packet in service.packets(32):
        sys.stdout.buffer.write(packet.bytes)

    # Modify the service if required
