#!/usr/bin/env python3

# An example of generating a service from scratch.

import sys
import numpy

from teletext.t42.service import Service
from teletext.t42.subpage import Subpage

# Create a subpage
subpage = Subpage()

# Add text to the subpage. Later there will be an API for this.
subpage.displayable[10:15,5] = numpy.fromstring('Hello', dtype=numpy.uint8)
subpage.displayable[10:15,6] = numpy.fromstring('World', dtype=numpy.uint8)

# Create the service
service = Service()

# Add the subpage to the service.
service.magazines[1].pages[0].subpages[0] = subpage

# Set magazine name and number
service.magazines[1].title = 'Example '
service.magazines[1].magazineno = 1

# Broadcast it forever
while True:
    for packet in service.next_packets(prio=[3,3,3,3,3,3,3,3]):
        sys.stdout.write(packet.to_bytes())

    #
    # Here you may add, remove, or modify elements of the service.
    #
