#!/usr/bin/env python3

import json
import re
import requests
from PIL import Image
import numpy as np

from teletext.subpage import Subpage


def get_sensors():
    url = "http://hms.nottinghack.org.uk/api/spaceapi"
    dat = json.loads(requests.get(url).text)
    return {s['location']: s["value"] for s in dat['sensors']['temperature']}


def colour(t):
    if t < 10:
        return '\x06'
    elif t < 20:
        return '\x02'
    elif t < 30:
        return '\x04'
    else:
        return '\x01'

def clean_name(s):
    s = s.split('/')[0].replace('-LLAP', '').replace('G5-', '')
    return re.sub(r'([^\s-])([A-Z])', r'\1 \2', s)

def tti():
    with open('template.t42', 'rb') as f:
        page = Subpage.from_file(f)

    page.header.page = 0
    page.header.control = 0

    layout = (
        ('Airlock', 'ComfyArea-LLAP'),
        ('Studio-LLAP', 'CraftRoom-LLAP'),
        ('Kitchen-LLAP', 'Workshop-LLAP'),
        ('ClassRoom', 'G5-BlueRoom-LLAP'),
    )

    i = Image.open("sensors.png").convert(mode="1")
    page.displayable.place_bitmap(np.array(i), 16, 2, 0x13)

    sensors = get_sensors()
    for n, l in enumerate(layout):
        clean_names = (clean_name(s)[:10] + ':' for s in l)
        string = '  \x07'.join(f'{c:11s}{colour(sensors[s])}{sensors[s]:4.1f}C' for c, s in zip(clean_names, l))
        page.displayable.place_string('\x0d'+string, 1, (3*n)+8) # 0d = double height

    page.displayable.place_string('\x02\x1d\x04Temperature readings from the space', 0, 21)
    page.displayable.place_string('\x02\x1d\x04See P123 for info about the heating', 0, 22)
    page.displayable.place_string('\x01Main Index   \x02News    \x03Events    \x06Tools', 0, 23)

    with open('P100.tti', 'w') as f:
        f.write(page.to_tti())

    print("https://zxnet.co.uk/teletext/editor/#" + page.url)

if __name__ == '__main__':
    tti()
